// Builds src/server/ports.ts, the names of the world's seaports from UN/LOCODE,
// the UN's code list for trade locations. UNECE publishes two releases a
// year; run `npm run ports` to pick up a new one.

import { writeFile } from 'node:fs/promises';

// A mirror of the UNECE release as a single CSV.
const SOURCE = 'https://raw.githubusercontent.com/datasets/un-locode/main/data/code-list.csv';
const OUT = new URL('../src/server/ports.ts', import.meta.url);

// UN/LOCODE uses local spellings. These are the ports an English reader
// knows by another name.
const ENGLISH: Readonly<Record<string, string>> = {
  BEANR: 'Antwerp',
  BEBRU: 'Brussels',
  BEGNE: 'Ghent',
  DKCPH: 'Copenhagen',
  ESSVQ: 'Seville',
  FRCER: 'Cherbourg',
  FRDKK: 'Dunkirk',
  ITGOA: 'Genoa',
  ITNAP: 'Naples',
  ITVCE: 'Venice',
  PTLIS: 'Lisbon',
  SEGOT: 'Gothenburg',
};

// Splits one CSV line, allowing for quoted fields with commas in them.
function fields(line: string): string[] {
  const matches = line.matchAll(/(?<=^|,)(?:"(?<quoted>(?:[^"]|"")*)"|(?<plain>[^,"]*))(?=,|$)/gv);
  return [...matches].map((m) => m.groups?.['quoted']?.replaceAll('""', '"') ?? m.groups?.['plain'] ?? '');
}

// "Ostend (Oostende)" and "IJmuiden/Velsen" read better as their first name.
function tidy(name: string): string {
  return (
    name
      .replace(/ \(.*\)$/v, '')
      .split('/')[0]
      ?.trim() ?? name
  );
}

async function download(): Promise<string[]> {
  const res = await fetch(SOURCE);
  if (!res.ok) {
    throw new Error(`${SOURCE} returned HTTP ${res.status}`);
  }
  const csv = await res.text();
  const [, ...lines] = csv.split(/\r?\n/v);
  return lines;
}

function portNames(lines: readonly string[]): Map<string, string> {
  const ports = new Map<string, string>();
  for (const line of lines) {
    // Change, Country, Location, Name, NameWoDiacritics, Subdivision, Status, Function
    const row = fields(line);
    const [change = '', country = '', location = '', name = ''] = row;
    const fn = row[7] ?? '';
    // A "1" in the first function slot marks a port; an "X" change marks an entry due to be removed.
    if (fn.startsWith('1') && change !== 'X') {
      const code = country + location;
      ports.set(code, ENGLISH[code] ?? tidy(name));
    }
  }
  return ports;
}

const ports = portNames(await download());
const body = [...ports]
  .toSorted(([a], [b]) => a.localeCompare(b))
  .map(([code, name]) => `  ${code}: ${JSON.stringify(name)},`)
  .join('\n');
await writeFile(
  OUT,
  `// Generated by scripts/ports.ts from UN/LOCODE. Don't edit by hand.\n\nconst PORTS: Readonly<Record<string, string>> = {\n${body}\n};\n\nexport { PORTS };\n`,
);
console.error(`Wrote ${ports.size} ports.`);
