// Builds src/client/thames.ts, the Thames centreline through the map area
// from OpenStreetMap. The browser moves boats along it between AIS reports.
// Run `npm run thames` if the default bounding box changes.

import { writeFile } from 'node:fs/promises';

const OVERPASS = 'https://overpass-api.de/api/interpreter';
// South, west, north, east: the default bounding box with room either side,
// so boats near its edges still have river ahead of them.
const AREA = [51.455, -0.085, 51.525, 0.045] as const;
// Points closer than this to a straight line between their neighbours are dropped.
const TOLERANCE_METRES = 2;
const OUT = new URL('../src/client/thames.ts', import.meta.url);

type Point = readonly [lon: number, lat: number];

interface Node {
  readonly lat: number;
  readonly lon: number;
}

interface Way {
  readonly geometry: readonly Node[];
}

// Overpass is the only source, so a light shape check is enough.
function isOverpassResult(value: unknown): value is { readonly elements: readonly Way[] } {
  return typeof value === 'object' && value !== null && 'elements' in value && Array.isArray(value.elements);
}

async function download(): Promise<readonly Way[]> {
  const [south, west, north, east] = AREA;
  const query = `[out:json];way["waterway"="river"]["name"="River Thames"](${south},${west},${north},${east});out geom;`;
  const res = await fetch(OVERPASS, {
    method: 'POST',
    // Overpass refuses requests without a user agent or Accept header.
    headers: { 'user-agent': 'greenwich-reach-watch (scripts/thames.ts)', accept: 'application/json' },
    body: new URLSearchParams({ data: query }),
  });
  if (!res.ok) {
    throw new Error(`Overpass returned HTTP ${res.status}`);
  }
  const result: unknown = await res.json();
  if (!isOverpassResult(result)) {
    throw new Error('Overpass returned something other than a list of ways');
  }
  return result.elements;
}

function key(node: Node | undefined): string {
  return node ? `${node.lat},${node.lon}` : '';
}

// OSM splits the river into ways that run downstream end to start. Joins them
// into one line from the westernmost (most upstream) way.
function join(ways: readonly Way[]): Point[] {
  const byStart = new Map(ways.map((w) => [key(w.geometry[0]), w]));
  const ends = new Set(ways.map((w) => key(w.geometry.at(-1))));
  const line: Point[] = [];
  for (let way = ways.find((w) => !ends.has(key(w.geometry[0]))); way; way = byStart.get(key(way.geometry.at(-1)))) {
    byStart.delete(key(way.geometry[0]));
    // Each way starts where the last one ended.
    line.push(...way.geometry.slice(line.length === 0 ? 0 : 1).map(({ lat, lon }): Point => [lon, lat]));
  }
  if (byStart.size > 0) {
    throw new Error(`${byStart.size} pieces of the river didn't join up`);
  }
  return line;
}

function inArea([lon, lat]: Point): boolean {
  const [south, west, north, east] = AREA;
  return lat >= south && lat <= north && lon >= west && lon <= east;
}

// The run of points from the first inside the area to the last.
function clip(line: readonly Point[]): Point[] {
  const start = line.findIndex((p) => inArea(p));
  const end = line.findLastIndex((p) => inArea(p));
  return line.slice(Math.max(start - 1, 0), end + 2);
}

function metres([lon, lat]: Point): readonly [number, number] {
  return [lon * 111_320 * Math.cos((lat * Math.PI) / 180), lat * 110_574];
}

function offLine(p: Point, a: Point, b: Point): number {
  const [px, py] = metres(p);
  const [ax, ay] = metres(a);
  const [bx, by] = metres(b);
  const length = Math.hypot(bx - ax, by - ay);
  return length === 0 ? Math.hypot(px - ax, py - ay) : Math.abs((bx - ax) * (ay - py) - (ax - px) * (by - ay)) / length;
}

// The point furthest from the straight line between the two ends.
function farthest(line: readonly Point[], first: Point, last: Point): { index: number; distance: number } {
  let worst = { index: 0, distance: 0 };
  for (const [index, p] of line.entries()) {
    const distance = offLine(p, first, last);
    if (distance > worst.distance) {
      worst = { index, distance };
    }
  }
  return worst;
}

// Douglas–Peucker.
function simplify(line: readonly Point[]): Point[] {
  const [first] = line;
  const last = line.at(-1);
  if (line.length < 3 || !first || !last) {
    return [...line];
  }
  const { index, distance } = farthest(line, first, last);
  if (distance <= TOLERANCE_METRES) {
    return [first, last];
  }
  return [...simplify(line.slice(0, index + 1)).slice(0, -1), ...simplify(line.slice(index))];
}

const ways = await download();
const river = simplify(clip(join(ways)));
const body = river.map(([lon, lat]) => `  [${Number(lon.toFixed(6))}, ${Number(lat.toFixed(6))}],`).join('\n');
await writeFile(
  OUT,
  `// Generated by scripts/thames.ts from OpenStreetMap (ODbL). Don't edit by hand.\n\n// The middle of the river as [longitude, latitude], flowing downstream.\nconst THAMES: readonly (readonly [number, number])[] = [\n${body}\n];\n\nexport { THAMES };\n`,
);
console.error(`Wrote ${river.length} points.`);
